# Generated by Django 5.0.3 on 2024-08-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_name',
        ),
    ]
